const natives: Set<object> = new Set<object>()

if (["object", "function"].includes(typeof AbortController) && AbortController !== null) natives.add(AbortController)
if (["object", "function"].includes(typeof AbortSignal) && AbortSignal !== null) natives.add(AbortSignal)
if (["object", "function"].includes(typeof AbstractRange) && AbstractRange !== null) natives.add(AbstractRange)
if (["object", "function"].includes(typeof ActiveXObject) && ActiveXObject !== null) natives.add(ActiveXObject)
if (["object", "function"].includes(typeof AnalyserNode) && AnalyserNode !== null) natives.add(AnalyserNode)
if (["object", "function"].includes(typeof Animation) && Animation !== null) natives.add(Animation)
if (["object", "function"].includes(typeof AnimationEffect) && AnimationEffect !== null) natives.add(AnimationEffect)
if (["object", "function"].includes(typeof AnimationEvent) && AnimationEvent !== null) natives.add(AnimationEvent)
if (["object", "function"].includes(typeof AnimationPlaybackEvent) && AnimationPlaybackEvent !== null) natives.add(AnimationPlaybackEvent)
if (["object", "function"].includes(typeof AnimationTimeline) && AnimationTimeline !== null) natives.add(AnimationTimeline)
if (["object", "function"].includes(typeof Array) && Array !== null) natives.add(Array)
if (["object", "function"].includes(typeof ArrayBuffer) && ArrayBuffer !== null) natives.add(ArrayBuffer)
if (["object", "function"].includes(typeof Atomics) && Atomics !== null) natives.add(Atomics)
if (["object", "function"].includes(typeof Attr) && Attr !== null) natives.add(Attr)
if (["object", "function"].includes(typeof Audio) && Audio !== null) natives.add(Audio)
if (["object", "function"].includes(typeof AudioBuffer) && AudioBuffer !== null) natives.add(AudioBuffer)
if (["object", "function"].includes(typeof AudioBufferSourceNode) && AudioBufferSourceNode !== null) natives.add(AudioBufferSourceNode)
if (["object", "function"].includes(typeof AudioContext) && AudioContext !== null) natives.add(AudioContext)
if (["object", "function"].includes(typeof AudioDestinationNode) && AudioDestinationNode !== null) natives.add(AudioDestinationNode)
if (["object", "function"].includes(typeof AudioListener) && AudioListener !== null) natives.add(AudioListener)
if (["object", "function"].includes(typeof AudioNode) && AudioNode !== null) natives.add(AudioNode)
if (["object", "function"].includes(typeof AudioParam) && AudioParam !== null) natives.add(AudioParam)
if (["object", "function"].includes(typeof AudioParamMap) && AudioParamMap !== null) natives.add(AudioParamMap)
if (["object", "function"].includes(typeof AudioScheduledSourceNode) && AudioScheduledSourceNode !== null) natives.add(AudioScheduledSourceNode)
if (["object", "function"].includes(typeof AudioWorklet) && AudioWorklet !== null) natives.add(AudioWorklet)
if (["object", "function"].includes(typeof AudioWorkletNode) && AudioWorkletNode !== null) natives.add(AudioWorkletNode)
if (["object", "function"].includes(typeof AuthenticatorAssertionResponse) && AuthenticatorAssertionResponse !== null) natives.add(AuthenticatorAssertionResponse)
if (["object", "function"].includes(typeof AuthenticatorAttestationResponse) && AuthenticatorAttestationResponse !== null) natives.add(AuthenticatorAttestationResponse)
if (["object", "function"].includes(typeof AuthenticatorResponse) && AuthenticatorResponse !== null) natives.add(AuthenticatorResponse)
if (["object", "function"].includes(typeof AudioProcessingEvent) && AudioProcessingEvent !== null) natives.add(AudioProcessingEvent)
if (["object", "function"].includes(typeof addEventListener) && addEventListener !== null) natives.add(addEventListener)
if (["object", "function"].includes(typeof afterAll) && afterAll !== null) natives.add(afterAll)
if (["object", "function"].includes(typeof afterEach) && afterEach !== null) natives.add(afterEach)
if (["object", "function"].includes(typeof alert) && alert !== null) natives.add(alert)
if (["object", "function"].includes(typeof atob) && atob !== null) natives.add(atob)

if (["object", "function"].includes(typeof BarProp) && BarProp !== null) natives.add(BarProp)
if (["object", "function"].includes(typeof BaseAudioContext) && BaseAudioContext !== null) natives.add(BaseAudioContext)
if (["object", "function"].includes(typeof BeforeUnloadEvent) && BeforeUnloadEvent !== null) natives.add(BeforeUnloadEvent)
if (["object", "function"].includes(typeof BigInt) && BigInt !== null) natives.add(BigInt)
if (["object", "function"].includes(typeof BigInt64Array) && BigInt64Array !== null) natives.add(BigInt64Array)
if (["object", "function"].includes(typeof BigUint64Array) && BigUint64Array !== null) natives.add(BigUint64Array)
if (["object", "function"].includes(typeof BiquadFilterNode) && BiquadFilterNode !== null) natives.add(BiquadFilterNode)
if (["object", "function"].includes(typeof Blob) && Blob !== null) natives.add(Blob)
if (["object", "function"].includes(typeof BlobEvent) && BlobEvent !== null) natives.add(BlobEvent)
if (["object", "function"].includes(typeof Boolean) && Boolean !== null) natives.add(Boolean)
if (["object", "function"].includes(typeof BroadcastChannel) && BroadcastChannel !== null) natives.add(BroadcastChannel)
if (["object", "function"].includes(typeof ByteLengthQueuingStrategy) && ByteLengthQueuingStrategy !== null) natives.add(ByteLengthQueuingStrategy)
if (["object", "function"].includes(typeof beforeAll) && beforeAll !== null) natives.add(beforeAll)
if (["object", "function"].includes(typeof beforeEach) && beforeEach !== null) natives.add(beforeEach)
if (["object", "function"].includes(typeof blur) && blur !== null) natives.add(blur)
if (["object", "function"].includes(typeof btoa) && btoa !== null) natives.add(btoa)

if (["object", "function"].includes(typeof CDATASection) && CDATASection !== null) natives.add(CDATASection)
if (["object", "function"].includes(typeof CSSAnimation) && CSSAnimation !== null) natives.add(CSSAnimation)
if (["object", "function"].includes(typeof CSSConditionRule) && CSSConditionRule !== null) natives.add(CSSConditionRule)
if (["object", "function"].includes(typeof CSSContainerRule) && CSSContainerRule !== null) natives.add(CSSContainerRule)
if (["object", "function"].includes(typeof CSSCounterStyleRule) && CSSCounterStyleRule !== null) natives.add(CSSCounterStyleRule)
if (["object", "function"].includes(typeof CSSFontFaceRule) && CSSFontFaceRule !== null) natives.add(CSSFontFaceRule)
if (["object", "function"].includes(typeof CSSFontPaletteValuesRule) && CSSFontPaletteValuesRule !== null) natives.add(CSSFontPaletteValuesRule)
if (["object", "function"].includes(typeof CSSGroupingRule) && CSSGroupingRule !== null) natives.add(CSSGroupingRule)
if (["object", "function"].includes(typeof CSSImportRule) && CSSImportRule !== null) natives.add(CSSImportRule)
if (["object", "function"].includes(typeof CSSKeyframeRule) && CSSKeyframeRule !== null) natives.add(CSSKeyframeRule)
if (["object", "function"].includes(typeof CSSKeyframesRule) && CSSKeyframesRule !== null) natives.add(CSSKeyframesRule)
if (["object", "function"].includes(typeof CSSLayerBlockRule) && CSSLayerBlockRule !== null) natives.add(CSSLayerBlockRule)
if (["object", "function"].includes(typeof CSSLayerStatementRule) && CSSLayerStatementRule !== null) natives.add(CSSLayerStatementRule)
if (["object", "function"].includes(typeof CSSMediaRule) && CSSMediaRule !== null) natives.add(CSSMediaRule)
if (["object", "function"].includes(typeof CSSNamespaceRule) && CSSNamespaceRule !== null) natives.add(CSSNamespaceRule)
if (["object", "function"].includes(typeof CSSPageRule) && CSSPageRule !== null) natives.add(CSSPageRule)
if (["object", "function"].includes(typeof CSSRule) && CSSRule !== null) natives.add(CSSRule)
if (["object", "function"].includes(typeof CSSRuleList) && CSSRuleList !== null) natives.add(CSSRuleList)
if (["object", "function"].includes(typeof CSSStyleDeclaration) && CSSStyleDeclaration !== null) natives.add(CSSStyleDeclaration)
if (["object", "function"].includes(typeof CSSStyleRule) && CSSStyleRule !== null) natives.add(CSSStyleRule)
if (["object", "function"].includes(typeof CSSStyleSheet) && CSSStyleSheet !== null) natives.add(CSSStyleSheet)
if (["object", "function"].includes(typeof CSSSupportsRule) && CSSSupportsRule !== null) natives.add(CSSSupportsRule)
if (["object", "function"].includes(typeof CSSTransition) && CSSTransition !== null) natives.add(CSSTransition)
if (["object", "function"].includes(typeof Cache) && Cache !== null) natives.add(Cache)
if (["object", "function"].includes(typeof CacheStorage) && CacheStorage !== null) natives.add(CacheStorage)
if (["object", "function"].includes(typeof CanvasCaptureMediaStreamTrack) && CanvasCaptureMediaStreamTrack !== null) natives.add(CanvasCaptureMediaStreamTrack)
if (["object", "function"].includes(typeof CanvasGradient) && CanvasGradient !== null) natives.add(CanvasGradient)
if (["object", "function"].includes(typeof CanvasPattern) && CanvasPattern !== null) natives.add(CanvasPattern)
if (["object", "function"].includes(typeof CanvasRenderingContext2D) && CanvasRenderingContext2D !== null) natives.add(CanvasRenderingContext2D)
if (["object", "function"].includes(typeof ChannelMergerNode) && ChannelMergerNode !== null) natives.add(ChannelMergerNode)
if (["object", "function"].includes(typeof ChannelSplitterNode) && ChannelSplitterNode !== null) natives.add(ChannelSplitterNode)
if (["object", "function"].includes(typeof CharacterData) && CharacterData !== null) natives.add(CharacterData)
if (["object", "function"].includes(typeof Clipboard) && Clipboard !== null) natives.add(Clipboard)
if (["object", "function"].includes(typeof ClipboardEvent) && ClipboardEvent !== null) natives.add(ClipboardEvent)
if (["object", "function"].includes(typeof ClipboardItem) && ClipboardItem !== null) natives.add(ClipboardItem)
if (["object", "function"].includes(typeof CloseEvent) && CloseEvent !== null) natives.add(CloseEvent)
if (["object", "function"].includes(typeof Comment) && Comment !== null) natives.add(Comment)
if (["object", "function"].includes(typeof CompositionEvent) && CompositionEvent !== null) natives.add(CompositionEvent)
if (["object", "function"].includes(typeof ConstantSourceNode) && ConstantSourceNode !== null) natives.add(ConstantSourceNode)
if (["object", "function"].includes(typeof ConvolverNode) && ConvolverNode !== null) natives.add(ConvolverNode)
if (["object", "function"].includes(typeof CountQueuingStrategy) && CountQueuingStrategy !== null) natives.add(CountQueuingStrategy)
if (["object", "function"].includes(typeof Credential) && Credential !== null) natives.add(Credential)
if (["object", "function"].includes(typeof CredentialsContainer) && CredentialsContainer !== null) natives.add(CredentialsContainer)
if (["object", "function"].includes(typeof Crypto) && Crypto !== null) natives.add(Crypto)
if (["object", "function"].includes(typeof CryptoKey) && CryptoKey !== null) natives.add(CryptoKey)
if (["object", "function"].includes(typeof CustomElementRegistry) && CustomElementRegistry !== null) natives.add(CustomElementRegistry)
if (["object", "function"].includes(typeof CustomEvent) && CustomEvent !== null) natives.add(CustomEvent)
if (["object", "function"].includes(typeof caches) && caches !== null) natives.add(caches)
if (["object", "function"].includes(typeof cancelAnimationFrame) && cancelAnimationFrame !== null) natives.add(cancelAnimationFrame)
if (["object", "function"].includes(typeof cancelIdleCallback) && cancelIdleCallback !== null) natives.add(cancelIdleCallback)
if (["object", "function"].includes(typeof clearInterval) && clearInterval !== null) natives.add(clearInterval)
if (["object", "function"].includes(typeof clearTimeout) && clearTimeout !== null) natives.add(clearTimeout)
if (["object", "function"].includes(typeof close) && close !== null) natives.add(close)
if (["object", "function"].includes(typeof confirm) && confirm !== null) natives.add(confirm)
if (["object", "function"].includes(typeof console) && console !== null) natives.add(console)
if (["object", "function"].includes(typeof createImageBitmap) && createImageBitmap !== null) natives.add(createImageBitmap)
if (["object", "function"].includes(typeof crypto) && crypto !== null) natives.add(crypto)
if (["object", "function"].includes(typeof customElements) && customElements !== null) natives.add(customElements)
if (["object", "function"].includes(typeof captureEvents) && captureEvents !== null) natives.add(captureEvents)
if (["object", "function"].includes(typeof clientInformation) && clientInformation !== null) natives.add(clientInformation)

if (["object", "function"].includes(typeof DOMException) && DOMException !== null) natives.add(DOMException)
if (["object", "function"].includes(typeof DOMImplementation) && DOMImplementation !== null) natives.add(DOMImplementation)
if (["object", "function"].includes(typeof DOMMatrix) && DOMMatrix !== null) natives.add(DOMMatrix)
if (["object", "function"].includes(typeof DOMMatrixReadOnly) && DOMMatrixReadOnly !== null) natives.add(DOMMatrixReadOnly)
if (["object", "function"].includes(typeof DOMParser) && DOMParser !== null) natives.add(DOMParser)
if (["object", "function"].includes(typeof DOMPoint) && DOMPoint !== null) natives.add(DOMPoint)
if (["object", "function"].includes(typeof DOMPointReadOnly) && DOMPointReadOnly !== null) natives.add(DOMPointReadOnly)
if (["object", "function"].includes(typeof DOMQuad) && DOMQuad !== null) natives.add(DOMQuad)
if (["object", "function"].includes(typeof DOMRect) && DOMRect !== null) natives.add(DOMRect)
if (["object", "function"].includes(typeof DOMRectList) && DOMRectList !== null) natives.add(DOMRectList)
if (["object", "function"].includes(typeof DOMRectReadOnly) && DOMRectReadOnly !== null) natives.add(DOMRectReadOnly)
if (["object", "function"].includes(typeof DOMStringList) && DOMStringList !== null) natives.add(DOMStringList)
if (["object", "function"].includes(typeof DOMStringMap) && DOMStringMap !== null) natives.add(DOMStringMap)
if (["object", "function"].includes(typeof DOMTokenList) && DOMTokenList !== null) natives.add(DOMTokenList)
if (["object", "function"].includes(typeof DataTransfer) && DataTransfer !== null) natives.add(DataTransfer)
if (["object", "function"].includes(typeof DataTransferItem) && DataTransferItem !== null) natives.add(DataTransferItem)
if (["object", "function"].includes(typeof DataTransferItemList) && DataTransferItemList !== null) natives.add(DataTransferItemList)
if (["object", "function"].includes(typeof DataView) && DataView !== null) natives.add(DataView)
if (["object", "function"].includes(typeof Date) && Date !== null) natives.add(Date)
if (["object", "function"].includes(typeof DelayNode) && DelayNode !== null) natives.add(DelayNode)
if (["object", "function"].includes(typeof DeviceMotionEvent) && DeviceMotionEvent !== null) natives.add(DeviceMotionEvent)
if (["object", "function"].includes(typeof DeviceOrientationEvent) && DeviceOrientationEvent !== null) natives.add(DeviceOrientationEvent)
if (["object", "function"].includes(typeof Document) && Document !== null) natives.add(Document)
if (["object", "function"].includes(typeof DocumentFragment) && DocumentFragment !== null) natives.add(DocumentFragment)
if (["object", "function"].includes(typeof DocumentTimeline) && DocumentTimeline !== null) natives.add(DocumentTimeline)
if (["object", "function"].includes(typeof DocumentType) && DocumentType !== null) natives.add(DocumentType)
if (["object", "function"].includes(typeof DragEvent) && DragEvent !== null) natives.add(DragEvent)
if (["object", "function"].includes(typeof DynamicsCompressorNode) && DynamicsCompressorNode !== null) natives.add(DynamicsCompressorNode)
if (["object", "function"].includes(typeof decodeURI) && decodeURI !== null) natives.add(decodeURI)
if (["object", "function"].includes(typeof decodeURIComponent) && decodeURIComponent !== null) natives.add(decodeURIComponent)
if (["object", "function"].includes(typeof describe) && describe !== null) natives.add(describe)
if (["object", "function"].includes(typeof dispatchEvent) && dispatchEvent !== null) natives.add(dispatchEvent)
if (["object", "function"].includes(typeof document) && document !== null) natives.add(document)

if (["object", "function"].includes(typeof Element) && Element !== null) natives.add(Element)
if (["object", "function"].includes(typeof ElementInternals) && ElementInternals !== null) natives.add(ElementInternals)
if (["object", "function"].includes(typeof Enumerator) && Enumerator !== null) natives.add(Enumerator)
if (["object", "function"].includes(typeof Error) && Error !== null) natives.add(Error)
if (["object", "function"].includes(typeof ErrorEvent) && ErrorEvent !== null) natives.add(ErrorEvent)
if (["object", "function"].includes(typeof EvalError) && EvalError !== null) natives.add(EvalError)
if (["object", "function"].includes(typeof Event) && Event !== null) natives.add(Event)
if (["object", "function"].includes(typeof EventCounts) && EventCounts !== null) natives.add(EventCounts)
if (["object", "function"].includes(typeof EventSource) && EventSource !== null) natives.add(EventSource)
if (["object", "function"].includes(typeof EventTarget) && EventTarget !== null) natives.add(EventTarget)
if (["object", "function"].includes(typeof External) && External !== null) natives.add(External)
if (["object", "function"].includes(typeof encodeURI) && encodeURI !== null) natives.add(encodeURI)
if (["object", "function"].includes(typeof encodeURIComponent) && encodeURIComponent !== null) natives.add(encodeURIComponent)
if (["object", "function"].includes(typeof eval) && eval !== null) natives.add(eval)
if (["object", "function"].includes(typeof expect) && expect !== null) natives.add(expect)
if (["object", "function"].includes(typeof escape) && escape !== null) natives.add(escape)
//@ts-ignore
if (["object", "function"].includes(typeof event) && event !== null) natives.add(event)
if (["object", "function"].includes(typeof external) && external !== null) natives.add(external)

if (["object", "function"].includes(typeof File) && File !== null) natives.add(File)
if (["object", "function"].includes(typeof FileList) && FileList !== null) natives.add(FileList)
if (["object", "function"].includes(typeof FileReader) && FileReader !== null) natives.add(FileReader)
if (["object", "function"].includes(typeof FileSystem) && FileSystem !== null) natives.add(FileSystem)
if (["object", "function"].includes(typeof FileSystemDirectoryEntry) && FileSystemDirectoryEntry !== null) natives.add(FileSystemDirectoryEntry)
if (["object", "function"].includes(typeof FileSystemDirectoryHandle) && FileSystemDirectoryHandle !== null) natives.add(FileSystemDirectoryHandle)
if (["object", "function"].includes(typeof FileSystemDirectoryReader) && FileSystemDirectoryReader !== null) natives.add(FileSystemDirectoryReader)
if (["object", "function"].includes(typeof FileSystemEntry) && FileSystemEntry !== null) natives.add(FileSystemEntry)
if (["object", "function"].includes(typeof FileSystemFileEntry) && FileSystemFileEntry !== null) natives.add(FileSystemFileEntry)
if (["object", "function"].includes(typeof FileSystemFileHandle) && FileSystemFileHandle !== null) natives.add(FileSystemFileHandle)
if (["object", "function"].includes(typeof FileSystemHandle) && FileSystemHandle !== null) natives.add(FileSystemHandle)
if (["object", "function"].includes(typeof Float32Array) && Float32Array !== null) natives.add(Float32Array)
if (["object", "function"].includes(typeof Float64Array) && Float64Array !== null) natives.add(Float64Array)
if (["object", "function"].includes(typeof FocusEvent) && FocusEvent !== null) natives.add(FocusEvent)
if (["object", "function"].includes(typeof FontFace) && FontFace !== null) natives.add(FontFace)
if (["object", "function"].includes(typeof FontFaceSet) && FontFaceSet !== null) natives.add(FontFaceSet)
if (["object", "function"].includes(typeof FontFaceSetLoadEvent) && FontFaceSetLoadEvent !== null) natives.add(FontFaceSetLoadEvent)
if (["object", "function"].includes(typeof FormData) && FormData !== null) natives.add(FormData)
if (["object", "function"].includes(typeof FormDataEvent) && FormDataEvent !== null) natives.add(FormDataEvent)
if (["object", "function"].includes(typeof Function) && Function !== null) natives.add(Function)
if (["object", "function"].includes(typeof fail) && fail !== null) natives.add(fail)
if (["object", "function"].includes(typeof fdescribe) && fdescribe !== null) natives.add(fdescribe)
if (["object", "function"].includes(typeof fetch) && fetch !== null) natives.add(fetch)
if (["object", "function"].includes(typeof fit) && fit !== null) natives.add(fit)
if (["object", "function"].includes(typeof focus) && focus !== null) natives.add(focus)
if (["object", "function"].includes(typeof frameElement) && frameElement !== null) natives.add(frameElement)
if (["object", "function"].includes(typeof frames) && frames !== null) natives.add(frames)

for (const object of natives) {

    const keys = Reflect.ownKeys(object)
    if ("constructor" in object)
        keys.push("constructor")

    for (const key of keys) {
        try {
            const value = Object.getOwnPropertyDescriptor(object, key)?.value || object[key]

            console.log(value)

            if (["object", "function"].includes(typeof value) && value !== null) {
                natives.add(value)
            }
        } catch { }
    }

}

export default Array.from(natives)