const natives: Set<object> = new Set<object>()

if (["object", "function"].includes(typeof AbortController) && AbortController !== null) natives.add(AbortController)
if (["object", "function"].includes(typeof AbortSignal) && AbortSignal !== null) natives.add(AbortSignal)
if (["object", "function"].includes(typeof AbstractRange) && AbstractRange !== null) natives.add(AbstractRange)
if (["object", "function"].includes(typeof ActiveXObject) && ActiveXObject !== null) natives.add(ActiveXObject)
if (["object", "function"].includes(typeof AnalyserNode) && AnalyserNode !== null) natives.add(AnalyserNode)
if (["object", "function"].includes(typeof Animation) && Animation !== null) natives.add(Animation)
if (["object", "function"].includes(typeof AnimationEffect) && AnimationEffect !== null) natives.add(AnimationEffect)
if (["object", "function"].includes(typeof AnimationEvent) && AnimationEvent !== null) natives.add(AnimationEvent)
if (["object", "function"].includes(typeof AnimationPlaybackEvent) && AnimationPlaybackEvent !== null) natives.add(AnimationPlaybackEvent)
if (["object", "function"].includes(typeof AnimationTimeline) && AnimationTimeline !== null) natives.add(AnimationTimeline)
if (["object", "function"].includes(typeof Array) && Array !== null) natives.add(Array)
if (["object", "function"].includes(typeof ArrayBuffer) && ArrayBuffer !== null) natives.add(ArrayBuffer)
if (["object", "function"].includes(typeof Atomics) && Atomics !== null) natives.add(Atomics)
if (["object", "function"].includes(typeof Attr) && Attr !== null) natives.add(Attr)
if (["object", "function"].includes(typeof Audio) && Audio !== null) natives.add(Audio)
if (["object", "function"].includes(typeof AudioBuffer) && AudioBuffer !== null) natives.add(AudioBuffer)
if (["object", "function"].includes(typeof AudioBufferSourceNode) && AudioBufferSourceNode !== null) natives.add(AudioBufferSourceNode)
if (["object", "function"].includes(typeof AudioContext) && AudioContext !== null) natives.add(AudioContext)
if (["object", "function"].includes(typeof AudioDestinationNode) && AudioDestinationNode !== null) natives.add(AudioDestinationNode)
if (["object", "function"].includes(typeof AudioListener) && AudioListener !== null) natives.add(AudioListener)
if (["object", "function"].includes(typeof AudioNode) && AudioNode !== null) natives.add(AudioNode)
if (["object", "function"].includes(typeof AudioParam) && AudioParam !== null) natives.add(AudioParam)
if (["object", "function"].includes(typeof AudioParamMap) && AudioParamMap !== null) natives.add(AudioParamMap)
if (["object", "function"].includes(typeof AudioScheduledSourceNode) && AudioScheduledSourceNode !== null) natives.add(AudioScheduledSourceNode)
if (["object", "function"].includes(typeof AudioWorklet) && AudioWorklet !== null) natives.add(AudioWorklet)
if (["object", "function"].includes(typeof AudioWorkletNode) && AudioWorkletNode !== null) natives.add(AudioWorkletNode)
if (["object", "function"].includes(typeof AuthenticatorAssertionResponse) && AuthenticatorAssertionResponse !== null) natives.add(AuthenticatorAssertionResponse)
if (["object", "function"].includes(typeof AuthenticatorAttestationResponse) && AuthenticatorAttestationResponse !== null) natives.add(AuthenticatorAttestationResponse)
if (["object", "function"].includes(typeof AuthenticatorResponse) && AuthenticatorResponse !== null) natives.add(AuthenticatorResponse)
if (["object", "function"].includes(typeof AudioProcessingEvent) && AudioProcessingEvent !== null) natives.add(AudioProcessingEvent)
if (["object", "function"].includes(typeof addEventListener) && addEventListener !== null) natives.add(addEventListener)
if (["object", "function"].includes(typeof alert) && alert !== null) natives.add(alert)
if (["object", "function"].includes(typeof atob) && atob !== null) natives.add(atob)

if (["object", "function"].includes(typeof BarProp) && BarProp !== null) natives.add(BarProp)
if (["object", "function"].includes(typeof BaseAudioContext) && BaseAudioContext !== null) natives.add(BaseAudioContext)
if (["object", "function"].includes(typeof BeforeUnloadEvent) && BeforeUnloadEvent !== null) natives.add(BeforeUnloadEvent)
if (["object", "function"].includes(typeof BigInt) && BigInt !== null) natives.add(BigInt)
if (["object", "function"].includes(typeof BigInt64Array) && BigInt64Array !== null) natives.add(BigInt64Array)
if (["object", "function"].includes(typeof BigUint64Array) && BigUint64Array !== null) natives.add(BigUint64Array)
if (["object", "function"].includes(typeof BiquadFilterNode) && BiquadFilterNode !== null) natives.add(BiquadFilterNode)
if (["object", "function"].includes(typeof Blob) && Blob !== null) natives.add(Blob)
if (["object", "function"].includes(typeof BlobEvent) && BlobEvent !== null) natives.add(BlobEvent)
if (["object", "function"].includes(typeof Boolean) && Boolean !== null) natives.add(Boolean)
if (["object", "function"].includes(typeof BroadcastChannel) && BroadcastChannel !== null) natives.add(BroadcastChannel)
if (["object", "function"].includes(typeof ByteLengthQueuingStrategy) && ByteLengthQueuingStrategy !== null) natives.add(ByteLengthQueuingStrategy)
if (["object", "function"].includes(typeof blur) && blur !== null) natives.add(blur)
if (["object", "function"].includes(typeof btoa) && btoa !== null) natives.add(btoa)

if (["object", "function"].includes(typeof CDATASection) && CDATASection !== null) natives.add(CDATASection)
if (["object", "function"].includes(typeof CSSAnimation) && CSSAnimation !== null) natives.add(CSSAnimation)
if (["object", "function"].includes(typeof CSSConditionRule) && CSSConditionRule !== null) natives.add(CSSConditionRule)
if (["object", "function"].includes(typeof CSSContainerRule) && CSSContainerRule !== null) natives.add(CSSContainerRule)
if (["object", "function"].includes(typeof CSSCounterStyleRule) && CSSCounterStyleRule !== null) natives.add(CSSCounterStyleRule)
if (["object", "function"].includes(typeof CSSFontFaceRule) && CSSFontFaceRule !== null) natives.add(CSSFontFaceRule)
if (["object", "function"].includes(typeof CSSFontPaletteValuesRule) && CSSFontPaletteValuesRule !== null) natives.add(CSSFontPaletteValuesRule)
if (["object", "function"].includes(typeof CSSGroupingRule) && CSSGroupingRule !== null) natives.add(CSSGroupingRule)
if (["object", "function"].includes(typeof CSSImportRule) && CSSImportRule !== null) natives.add(CSSImportRule)
if (["object", "function"].includes(typeof CSSKeyframeRule) && CSSKeyframeRule !== null) natives.add(CSSKeyframeRule)
if (["object", "function"].includes(typeof CSSKeyframesRule) && CSSKeyframesRule !== null) natives.add(CSSKeyframesRule)
if (["object", "function"].includes(typeof CSSLayerBlockRule) && CSSLayerBlockRule !== null) natives.add(CSSLayerBlockRule)
if (["object", "function"].includes(typeof CSSLayerStatementRule) && CSSLayerStatementRule !== null) natives.add(CSSLayerStatementRule)
if (["object", "function"].includes(typeof CSSMediaRule) && CSSMediaRule !== null) natives.add(CSSMediaRule)
if (["object", "function"].includes(typeof CSSNamespaceRule) && CSSNamespaceRule !== null) natives.add(CSSNamespaceRule)
if (["object", "function"].includes(typeof CSSPageRule) && CSSPageRule !== null) natives.add(CSSPageRule)
if (["object", "function"].includes(typeof CSSRule) && CSSRule !== null) natives.add(CSSRule)
if (["object", "function"].includes(typeof CSSRuleList) && CSSRuleList !== null) natives.add(CSSRuleList)
if (["object", "function"].includes(typeof CSSStyleDeclaration) && CSSStyleDeclaration !== null) natives.add(CSSStyleDeclaration)
if (["object", "function"].includes(typeof CSSStyleRule) && CSSStyleRule !== null) natives.add(CSSStyleRule)
if (["object", "function"].includes(typeof CSSStyleSheet) && CSSStyleSheet !== null) natives.add(CSSStyleSheet)
if (["object", "function"].includes(typeof CSSSupportsRule) && CSSSupportsRule !== null) natives.add(CSSSupportsRule)
if (["object", "function"].includes(typeof CSSTransition) && CSSTransition !== null) natives.add(CSSTransition)
if (["object", "function"].includes(typeof Cache) && Cache !== null) natives.add(Cache)
if (["object", "function"].includes(typeof CacheStorage) && CacheStorage !== null) natives.add(CacheStorage)
if (["object", "function"].includes(typeof CanvasCaptureMediaStreamTrack) && CanvasCaptureMediaStreamTrack !== null) natives.add(CanvasCaptureMediaStreamTrack)
if (["object", "function"].includes(typeof CanvasGradient) && CanvasGradient !== null) natives.add(CanvasGradient)
if (["object", "function"].includes(typeof CanvasPattern) && CanvasPattern !== null) natives.add(CanvasPattern)
if (["object", "function"].includes(typeof CanvasRenderingContext2D) && CanvasRenderingContext2D !== null) natives.add(CanvasRenderingContext2D)
if (["object", "function"].includes(typeof ChannelMergerNode) && ChannelMergerNode !== null) natives.add(ChannelMergerNode)
if (["object", "function"].includes(typeof ChannelSplitterNode) && ChannelSplitterNode !== null) natives.add(ChannelSplitterNode)
if (["object", "function"].includes(typeof CharacterData) && CharacterData !== null) natives.add(CharacterData)
if (["object", "function"].includes(typeof Clipboard) && Clipboard !== null) natives.add(Clipboard)
if (["object", "function"].includes(typeof ClipboardEvent) && ClipboardEvent !== null) natives.add(ClipboardEvent)
if (["object", "function"].includes(typeof ClipboardItem) && ClipboardItem !== null) natives.add(ClipboardItem)
if (["object", "function"].includes(typeof CloseEvent) && CloseEvent !== null) natives.add(CloseEvent)
if (["object", "function"].includes(typeof Comment) && Comment !== null) natives.add(Comment)
if (["object", "function"].includes(typeof CompositionEvent) && CompositionEvent !== null) natives.add(CompositionEvent)
if (["object", "function"].includes(typeof ConstantSourceNode) && ConstantSourceNode !== null) natives.add(ConstantSourceNode)
if (["object", "function"].includes(typeof ConvolverNode) && ConvolverNode !== null) natives.add(ConvolverNode)
if (["object", "function"].includes(typeof CountQueuingStrategy) && CountQueuingStrategy !== null) natives.add(CountQueuingStrategy)
if (["object", "function"].includes(typeof Credential) && Credential !== null) natives.add(Credential)
if (["object", "function"].includes(typeof CredentialsContainer) && CredentialsContainer !== null) natives.add(CredentialsContainer)
if (["object", "function"].includes(typeof Crypto) && Crypto !== null) natives.add(Crypto)
if (["object", "function"].includes(typeof CryptoKey) && CryptoKey !== null) natives.add(CryptoKey)
if (["object", "function"].includes(typeof CustomElementRegistry) && CustomElementRegistry !== null) natives.add(CustomElementRegistry)
if (["object", "function"].includes(typeof CustomEvent) && CustomEvent !== null) natives.add(CustomEvent)
if (["object", "function"].includes(typeof caches) && caches !== null) natives.add(caches)
if (["object", "function"].includes(typeof cancelAnimationFrame) && cancelAnimationFrame !== null) natives.add(cancelAnimationFrame)
if (["object", "function"].includes(typeof cancelIdleCallback) && cancelIdleCallback !== null) natives.add(cancelIdleCallback)
if (["object", "function"].includes(typeof clearInterval) && clearInterval !== null) natives.add(clearInterval)
if (["object", "function"].includes(typeof clearTimeout) && clearTimeout !== null) natives.add(clearTimeout)
if (["object", "function"].includes(typeof close) && close !== null) natives.add(close)
if (["object", "function"].includes(typeof confirm) && confirm !== null) natives.add(confirm)
if (["object", "function"].includes(typeof console) && console !== null) natives.add(console)
if (["object", "function"].includes(typeof createImageBitmap) && createImageBitmap !== null) natives.add(createImageBitmap)
if (["object", "function"].includes(typeof crypto) && crypto !== null) natives.add(crypto)
if (["object", "function"].includes(typeof customElements) && customElements !== null) natives.add(customElements)
if (["object", "function"].includes(typeof captureEvents) && captureEvents !== null) natives.add(captureEvents)
if (["object", "function"].includes(typeof clientInformation) && clientInformation !== null) natives.add(clientInformation)

if (["object", "function"].includes(typeof DOMException) && DOMException !== null) natives.add(DOMException)
if (["object", "function"].includes(typeof DOMImplementation) && DOMImplementation !== null) natives.add(DOMImplementation)
if (["object", "function"].includes(typeof DOMMatrix) && DOMMatrix !== null) natives.add(DOMMatrix)
if (["object", "function"].includes(typeof DOMMatrixReadOnly) && DOMMatrixReadOnly !== null) natives.add(DOMMatrixReadOnly)
if (["object", "function"].includes(typeof DOMParser) && DOMParser !== null) natives.add(DOMParser)
if (["object", "function"].includes(typeof DOMPoint) && DOMPoint !== null) natives.add(DOMPoint)
if (["object", "function"].includes(typeof DOMPointReadOnly) && DOMPointReadOnly !== null) natives.add(DOMPointReadOnly)
if (["object", "function"].includes(typeof DOMQuad) && DOMQuad !== null) natives.add(DOMQuad)
if (["object", "function"].includes(typeof DOMRect) && DOMRect !== null) natives.add(DOMRect)
if (["object", "function"].includes(typeof DOMRectList) && DOMRectList !== null) natives.add(DOMRectList)
if (["object", "function"].includes(typeof DOMRectReadOnly) && DOMRectReadOnly !== null) natives.add(DOMRectReadOnly)
if (["object", "function"].includes(typeof DOMStringList) && DOMStringList !== null) natives.add(DOMStringList)
if (["object", "function"].includes(typeof DOMStringMap) && DOMStringMap !== null) natives.add(DOMStringMap)
if (["object", "function"].includes(typeof DOMTokenList) && DOMTokenList !== null) natives.add(DOMTokenList)
if (["object", "function"].includes(typeof DataTransfer) && DataTransfer !== null) natives.add(DataTransfer)
if (["object", "function"].includes(typeof DataTransferItem) && DataTransferItem !== null) natives.add(DataTransferItem)
if (["object", "function"].includes(typeof DataTransferItemList) && DataTransferItemList !== null) natives.add(DataTransferItemList)
if (["object", "function"].includes(typeof DataView) && DataView !== null) natives.add(DataView)
if (["object", "function"].includes(typeof Date) && Date !== null) natives.add(Date)
if (["object", "function"].includes(typeof DelayNode) && DelayNode !== null) natives.add(DelayNode)
if (["object", "function"].includes(typeof DeviceMotionEvent) && DeviceMotionEvent !== null) natives.add(DeviceMotionEvent)
if (["object", "function"].includes(typeof DeviceOrientationEvent) && DeviceOrientationEvent !== null) natives.add(DeviceOrientationEvent)
if (["object", "function"].includes(typeof Document) && Document !== null) natives.add(Document)
if (["object", "function"].includes(typeof DocumentFragment) && DocumentFragment !== null) natives.add(DocumentFragment)
if (["object", "function"].includes(typeof DocumentTimeline) && DocumentTimeline !== null) natives.add(DocumentTimeline)
if (["object", "function"].includes(typeof DocumentType) && DocumentType !== null) natives.add(DocumentType)
if (["object", "function"].includes(typeof DragEvent) && DragEvent !== null) natives.add(DragEvent)
if (["object", "function"].includes(typeof DynamicsCompressorNode) && DynamicsCompressorNode !== null) natives.add(DynamicsCompressorNode)
if (["object", "function"].includes(typeof decodeURI) && decodeURI !== null) natives.add(decodeURI)
if (["object", "function"].includes(typeof decodeURIComponent) && decodeURIComponent !== null) natives.add(decodeURIComponent)
if (["object", "function"].includes(typeof dispatchEvent) && dispatchEvent !== null) natives.add(dispatchEvent)
if (["object", "function"].includes(typeof document) && document !== null) natives.add(document)

if (["object", "function"].includes(typeof Element) && Element !== null) natives.add(Element)
if (["object", "function"].includes(typeof ElementInternals) && ElementInternals !== null) natives.add(ElementInternals)
if (["object", "function"].includes(typeof Enumerator) && Enumerator !== null) natives.add(Enumerator)
if (["object", "function"].includes(typeof Error) && Error !== null) natives.add(Error)
if (["object", "function"].includes(typeof ErrorEvent) && ErrorEvent !== null) natives.add(ErrorEvent)
if (["object", "function"].includes(typeof EvalError) && EvalError !== null) natives.add(EvalError)
if (["object", "function"].includes(typeof Event) && Event !== null) natives.add(Event)
if (["object", "function"].includes(typeof EventCounts) && EventCounts !== null) natives.add(EventCounts)
if (["object", "function"].includes(typeof EventSource) && EventSource !== null) natives.add(EventSource)
if (["object", "function"].includes(typeof EventTarget) && EventTarget !== null) natives.add(EventTarget)
if (["object", "function"].includes(typeof External) && External !== null) natives.add(External)
if (["object", "function"].includes(typeof encodeURI) && encodeURI !== null) natives.add(encodeURI)
if (["object", "function"].includes(typeof encodeURIComponent) && encodeURIComponent !== null) natives.add(encodeURIComponent)
if (["object", "function"].includes(typeof eval) && eval !== null) natives.add(eval)
if (["object", "function"].includes(typeof escape) && escape !== null) natives.add(escape)
if (["object", "function"].includes(typeof event) && event !== null) natives.add(event)
if (["object", "function"].includes(typeof external) && external !== null) natives.add(external)

if (["object", "function"].includes(typeof File) && File !== null) natives.add(File)
if (["object", "function"].includes(typeof FileList) && FileList !== null) natives.add(FileList)
if (["object", "function"].includes(typeof FileReader) && FileReader !== null) natives.add(FileReader)
if (["object", "function"].includes(typeof FileSystem) && FileSystem !== null) natives.add(FileSystem)
if (["object", "function"].includes(typeof FileSystemDirectoryEntry) && FileSystemDirectoryEntry !== null) natives.add(FileSystemDirectoryEntry)
if (["object", "function"].includes(typeof FileSystemDirectoryHandle) && FileSystemDirectoryHandle !== null) natives.add(FileSystemDirectoryHandle)
if (["object", "function"].includes(typeof FileSystemDirectoryReader) && FileSystemDirectoryReader !== null) natives.add(FileSystemDirectoryReader)
if (["object", "function"].includes(typeof FileSystemEntry) && FileSystemEntry !== null) natives.add(FileSystemEntry)
if (["object", "function"].includes(typeof FileSystemFileEntry) && FileSystemFileEntry !== null) natives.add(FileSystemFileEntry)
if (["object", "function"].includes(typeof FileSystemFileHandle) && FileSystemFileHandle !== null) natives.add(FileSystemFileHandle)
if (["object", "function"].includes(typeof FileSystemHandle) && FileSystemHandle !== null) natives.add(FileSystemHandle)
if (["object", "function"].includes(typeof Float32Array) && Float32Array !== null) natives.add(Float32Array)
if (["object", "function"].includes(typeof Float64Array) && Float64Array !== null) natives.add(Float64Array)
if (["object", "function"].includes(typeof FocusEvent) && FocusEvent !== null) natives.add(FocusEvent)
if (["object", "function"].includes(typeof FontFace) && FontFace !== null) natives.add(FontFace)
if (["object", "function"].includes(typeof FontFaceSet) && FontFaceSet !== null) natives.add(FontFaceSet)
if (["object", "function"].includes(typeof FontFaceSetLoadEvent) && FontFaceSetLoadEvent !== null) natives.add(FontFaceSetLoadEvent)
if (["object", "function"].includes(typeof FormData) && FormData !== null) natives.add(FormData)
if (["object", "function"].includes(typeof FormDataEvent) && FormDataEvent !== null) natives.add(FormDataEvent)
if (["object", "function"].includes(typeof Function) && Function !== null) natives.add(Function)
if (["object", "function"].includes(typeof fetch) && fetch !== null) natives.add(fetch)
if (["object", "function"].includes(typeof focus) && focus !== null) natives.add(focus)
if (["object", "function"].includes(typeof frameElement) && frameElement !== null) natives.add(frameElement)
if (["object", "function"].includes(typeof frames) && frames !== null) natives.add(frames)

if (["object", "function"].includes(typeof GainNode) && GainNode !== null) natives.add(GainNode)
if (["object", "function"].includes(typeof Gamepad) && Gamepad !== null) natives.add(Gamepad)
if (["object", "function"].includes(typeof GamepadButton) && GamepadButton !== null) natives.add(GamepadButton)
if (["object", "function"].includes(typeof GamepadEvent) && GamepadEvent !== null) natives.add(GamepadEvent)
if (["object", "function"].includes(typeof GamepadHapticActuator) && GamepadHapticActuator !== null) natives.add(GamepadHapticActuator)
if (["object", "function"].includes(typeof Geolocation) && Geolocation !== null) natives.add(Geolocation)
if (["object", "function"].includes(typeof GeolocationCoordinates) && GeolocationCoordinates !== null) natives.add(GeolocationCoordinates)
if (["object", "function"].includes(typeof GeolocationPosition) && GeolocationPosition !== null) natives.add(GeolocationPosition)
if (["object", "function"].includes(typeof GeolocationPositionError) && GeolocationPositionError !== null) natives.add(GeolocationPositionError)
if (["object", "function"].includes(typeof getComputedStyle) && getComputedStyle !== null) natives.add(getComputedStyle)
if (["object", "function"].includes(typeof getSelection) && getSelection !== null) natives.add(getSelection)

if (["object", "function"].includes(typeof HTMLAllCollection) && HTMLAllCollection !== null) natives.add(HTMLAllCollection)
if (["object", "function"].includes(typeof HTMLAnchorElement) && HTMLAnchorElement !== null) natives.add(HTMLAnchorElement)
if (["object", "function"].includes(typeof HTMLAreaElement) && HTMLAreaElement !== null) natives.add(HTMLAreaElement)
if (["object", "function"].includes(typeof HTMLAudioElement) && HTMLAudioElement !== null) natives.add(HTMLAudioElement)
if (["object", "function"].includes(typeof HTMLBRElement) && HTMLBRElement !== null) natives.add(HTMLBRElement)
if (["object", "function"].includes(typeof HTMLBaseElement) && HTMLBaseElement !== null) natives.add(HTMLBaseElement)
if (["object", "function"].includes(typeof HTMLBodyElement) && HTMLBodyElement !== null) natives.add(HTMLBodyElement)
if (["object", "function"].includes(typeof HTMLButtonElement) && HTMLButtonElement !== null) natives.add(HTMLButtonElement)
if (["object", "function"].includes(typeof HTMLCanvasElement) && HTMLCanvasElement !== null) natives.add(HTMLCanvasElement)
if (["object", "function"].includes(typeof HTMLCollection) && HTMLCollection !== null) natives.add(HTMLCollection)
if (["object", "function"].includes(typeof HTMLDListElement) && HTMLDListElement !== null) natives.add(HTMLDListElement)
if (["object", "function"].includes(typeof HTMLDataElement) && HTMLDataElement !== null) natives.add(HTMLDataElement)
if (["object", "function"].includes(typeof HTMLDataListElement) && HTMLDataListElement !== null) natives.add(HTMLDataListElement)
if (["object", "function"].includes(typeof HTMLDetailsElement) && HTMLDetailsElement !== null) natives.add(HTMLDetailsElement)
if (["object", "function"].includes(typeof HTMLDialogElement) && HTMLDialogElement !== null) natives.add(HTMLDialogElement)
if (["object", "function"].includes(typeof HTMLDivElement) && HTMLDivElement !== null) natives.add(HTMLDivElement)
if (["object", "function"].includes(typeof HTMLElement) && HTMLElement !== null) natives.add(HTMLElement)
if (["object", "function"].includes(typeof HTMLEmbedElement) && HTMLEmbedElement !== null) natives.add(HTMLEmbedElement)
if (["object", "function"].includes(typeof HTMLFieldSetElement) && HTMLFieldSetElement !== null) natives.add(HTMLFieldSetElement)
if (["object", "function"].includes(typeof HTMLFormControlsCollection) && HTMLFormControlsCollection !== null) natives.add(HTMLFormControlsCollection)
if (["object", "function"].includes(typeof HTMLFormElement) && HTMLFormElement !== null) natives.add(HTMLFormElement)
if (["object", "function"].includes(typeof HTMLHRElement) && HTMLHRElement !== null) natives.add(HTMLHRElement)
if (["object", "function"].includes(typeof HTMLHeadElement) && HTMLHeadElement !== null) natives.add(HTMLHeadElement)
if (["object", "function"].includes(typeof HTMLHeadingElement) && HTMLHeadingElement !== null) natives.add(HTMLHeadingElement)
if (["object", "function"].includes(typeof HTMLHtmlElement) && HTMLHtmlElement !== null) natives.add(HTMLHtmlElement)
if (["object", "function"].includes(typeof HTMLIFrameElement) && HTMLIFrameElement !== null) natives.add(HTMLIFrameElement)
if (["object", "function"].includes(typeof HTMLImageElement) && HTMLImageElement !== null) natives.add(HTMLImageElement)
if (["object", "function"].includes(typeof HTMLInputElement) && HTMLInputElement !== null) natives.add(HTMLInputElement)
if (["object", "function"].includes(typeof HTMLLIElement) && HTMLLIElement !== null) natives.add(HTMLLIElement)
if (["object", "function"].includes(typeof HTMLLabelElement) && HTMLLabelElement !== null) natives.add(HTMLLabelElement)
if (["object", "function"].includes(typeof HTMLLegendElement) && HTMLLegendElement !== null) natives.add(HTMLLegendElement)
if (["object", "function"].includes(typeof HTMLLinkElement) && HTMLLinkElement !== null) natives.add(HTMLLinkElement)
if (["object", "function"].includes(typeof HTMLMapElement) && HTMLMapElement !== null) natives.add(HTMLMapElement)
if (["object", "function"].includes(typeof HTMLMediaElement) && HTMLMediaElement !== null) natives.add(HTMLMediaElement)
if (["object", "function"].includes(typeof HTMLMenuElement) && HTMLMenuElement !== null) natives.add(HTMLMenuElement)
if (["object", "function"].includes(typeof HTMLMetaElement) && HTMLMetaElement !== null) natives.add(HTMLMetaElement)
if (["object", "function"].includes(typeof HTMLMeterElement) && HTMLMeterElement !== null) natives.add(HTMLMeterElement)
if (["object", "function"].includes(typeof HTMLModElement) && HTMLModElement !== null) natives.add(HTMLModElement)
if (["object", "function"].includes(typeof HTMLOListElement) && HTMLOListElement !== null) natives.add(HTMLOListElement)
if (["object", "function"].includes(typeof HTMLObjectElement) && HTMLObjectElement !== null) natives.add(HTMLObjectElement)
if (["object", "function"].includes(typeof HTMLOptGroupElement) && HTMLOptGroupElement !== null) natives.add(HTMLOptGroupElement)
if (["object", "function"].includes(typeof HTMLOptionElement) && HTMLOptionElement !== null) natives.add(HTMLOptionElement)
if (["object", "function"].includes(typeof HTMLOptionsCollection) && HTMLOptionsCollection !== null) natives.add(HTMLOptionsCollection)
if (["object", "function"].includes(typeof HTMLOutputElement) && HTMLOutputElement !== null) natives.add(HTMLOutputElement)
if (["object", "function"].includes(typeof HTMLParagraphElement) && HTMLParagraphElement !== null) natives.add(HTMLParagraphElement)
if (["object", "function"].includes(typeof HTMLPictureElement) && HTMLPictureElement !== null) natives.add(HTMLPictureElement)
if (["object", "function"].includes(typeof HTMLPreElement) && HTMLPreElement !== null) natives.add(HTMLPreElement)
if (["object", "function"].includes(typeof HTMLProgressElement) && HTMLProgressElement !== null) natives.add(HTMLProgressElement)
if (["object", "function"].includes(typeof HTMLQuoteElement) && HTMLQuoteElement !== null) natives.add(HTMLQuoteElement)
if (["object", "function"].includes(typeof HTMLScriptElement) && HTMLScriptElement !== null) natives.add(HTMLScriptElement)
if (["object", "function"].includes(typeof HTMLSelectElement) && HTMLSelectElement !== null) natives.add(HTMLSelectElement)
if (["object", "function"].includes(typeof HTMLSlotElement) && HTMLSlotElement !== null) natives.add(HTMLSlotElement)
if (["object", "function"].includes(typeof HTMLSourceElement) && HTMLSourceElement !== null) natives.add(HTMLSourceElement)
if (["object", "function"].includes(typeof HTMLSpanElement) && HTMLSpanElement !== null) natives.add(HTMLSpanElement)
if (["object", "function"].includes(typeof HTMLStyleElement) && HTMLStyleElement !== null) natives.add(HTMLStyleElement)
if (["object", "function"].includes(typeof HTMLTableCaptionElement) && HTMLTableCaptionElement !== null) natives.add(HTMLTableCaptionElement)
if (["object", "function"].includes(typeof HTMLTableCellElement) && HTMLTableCellElement !== null) natives.add(HTMLTableCellElement)
if (["object", "function"].includes(typeof HTMLTableColElement) && HTMLTableColElement !== null) natives.add(HTMLTableColElement)
if (["object", "function"].includes(typeof HTMLTableElement) && HTMLTableElement !== null) natives.add(HTMLTableElement)
if (["object", "function"].includes(typeof HTMLTableRowElement) && HTMLTableRowElement !== null) natives.add(HTMLTableRowElement)
if (["object", "function"].includes(typeof HTMLTableSectionElement) && HTMLTableSectionElement !== null) natives.add(HTMLTableSectionElement)
if (["object", "function"].includes(typeof HTMLTemplateElement) && HTMLTemplateElement !== null) natives.add(HTMLTemplateElement)
if (["object", "function"].includes(typeof HTMLTextAreaElement) && HTMLTextAreaElement !== null) natives.add(HTMLTextAreaElement)
if (["object", "function"].includes(typeof HTMLTimeElement) && HTMLTimeElement !== null) natives.add(HTMLTimeElement)
if (["object", "function"].includes(typeof HTMLTitleElement) && HTMLTitleElement !== null) natives.add(HTMLTitleElement)
if (["object", "function"].includes(typeof HTMLTrackElement) && HTMLTrackElement !== null) natives.add(HTMLTrackElement)
if (["object", "function"].includes(typeof HTMLUListElement) && HTMLUListElement !== null) natives.add(HTMLUListElement)
if (["object", "function"].includes(typeof HTMLUnknownElement) && HTMLUnknownElement !== null) natives.add(HTMLUnknownElement)
if (["object", "function"].includes(typeof HTMLVideoElement) && HTMLVideoElement !== null) natives.add(HTMLVideoElement)
if (["object", "function"].includes(typeof HashChangeEvent) && HashChangeEvent !== null) natives.add(HashChangeEvent)
if (["object", "function"].includes(typeof Headers) && Headers !== null) natives.add(Headers)
if (["object", "function"].includes(typeof History) && History !== null) natives.add(History)
if (["object", "function"].includes(typeof HTMLDirectoryElement) && HTMLDirectoryElement !== null) natives.add(HTMLDirectoryElement)
if (["object", "function"].includes(typeof HTMLDocument) && HTMLDocument !== null) natives.add(HTMLDocument)
if (["object", "function"].includes(typeof HTMLFontElement) && HTMLFontElement !== null) natives.add(HTMLFontElement)
if (["object", "function"].includes(typeof HTMLFrameElement) && HTMLFrameElement !== null) natives.add(HTMLFrameElement)
if (["object", "function"].includes(typeof HTMLFrameSetElement) && HTMLFrameSetElement !== null) natives.add(HTMLFrameSetElement)
if (["object", "function"].includes(typeof HTMLMarqueeElement) && HTMLMarqueeElement !== null) natives.add(HTMLMarqueeElement)
if (["object", "function"].includes(typeof HTMLParamElement) && HTMLParamElement !== null) natives.add(HTMLParamElement)
if (["object", "function"].includes(typeof history) && history !== null) natives.add(history)

if (["object", "function"].includes(typeof IDBCursor) && IDBCursor !== null) natives.add(IDBCursor)
if (["object", "function"].includes(typeof IDBCursorWithValue) && IDBCursorWithValue !== null) natives.add(IDBCursorWithValue)
if (["object", "function"].includes(typeof IDBDatabase) && IDBDatabase !== null) natives.add(IDBDatabase)
if (["object", "function"].includes(typeof IDBFactory) && IDBFactory !== null) natives.add(IDBFactory)
if (["object", "function"].includes(typeof IDBIndex) && IDBIndex !== null) natives.add(IDBIndex)
if (["object", "function"].includes(typeof IDBKeyRange) && IDBKeyRange !== null) natives.add(IDBKeyRange)
if (["object", "function"].includes(typeof IDBObjectStore) && IDBObjectStore !== null) natives.add(IDBObjectStore)
if (["object", "function"].includes(typeof IDBOpenDBRequest) && IDBOpenDBRequest !== null) natives.add(IDBOpenDBRequest)
if (["object", "function"].includes(typeof IDBRequest) && IDBRequest !== null) natives.add(IDBRequest)
if (["object", "function"].includes(typeof IDBTransaction) && IDBTransaction !== null) natives.add(IDBTransaction)
if (["object", "function"].includes(typeof IDBVersionChangeEvent) && IDBVersionChangeEvent !== null) natives.add(IDBVersionChangeEvent)
if (["object", "function"].includes(typeof IIRFilterNode) && IIRFilterNode !== null) natives.add(IIRFilterNode)
if (["object", "function"].includes(typeof IdleDeadline) && IdleDeadline !== null) natives.add(IdleDeadline)
if (["object", "function"].includes(typeof Image) && Image !== null) natives.add(Image)
if (["object", "function"].includes(typeof ImageBitmap) && ImageBitmap !== null) natives.add(ImageBitmap)
if (["object", "function"].includes(typeof ImageBitmapRenderingContext) && ImageBitmapRenderingContext !== null) natives.add(ImageBitmapRenderingContext)
if (["object", "function"].includes(typeof ImageData) && ImageData !== null) natives.add(ImageData)
if (["object", "function"].includes(typeof InputDeviceInfo) && InputDeviceInfo !== null) natives.add(InputDeviceInfo)
if (["object", "function"].includes(typeof InputEvent) && InputEvent !== null) natives.add(InputEvent)
if (["object", "function"].includes(typeof Int16Array) && Int16Array !== null) natives.add(Int16Array)
if (["object", "function"].includes(typeof Int32Array) && Int32Array !== null) natives.add(Int32Array)
if (["object", "function"].includes(typeof Int8Array) && Int8Array !== null) natives.add(Int8Array)
if (["object", "function"].includes(typeof IntersectionObserver) && IntersectionObserver !== null) natives.add(IntersectionObserver)
if (["object", "function"].includes(typeof IntersectionObserverEntry) && IntersectionObserverEntry !== null) natives.add(IntersectionObserverEntry)
if (["object", "function"].includes(typeof importScripts) && importScripts !== null) natives.add(importScripts)
if (["object", "function"].includes(typeof indexedDB) && indexedDB !== null) natives.add(indexedDB)
if (["object", "function"].includes(typeof isFinite) && isFinite !== null) natives.add(isFinite)
if (["object", "function"].includes(typeof isNaN) && isNaN !== null) natives.add(isNaN)

if (["object", "function"].includes(typeof JSON) && JSON !== null) natives.add(JSON)

if (["object", "function"].includes(typeof KeyboardEvent) && KeyboardEvent !== null) natives.add(KeyboardEvent)
if (["object", "function"].includes(typeof KeyframeEffect) && KeyframeEffect !== null) natives.add(KeyframeEffect)

if (["object", "function"].includes(typeof Location) && Location !== null) natives.add(Location)
if (["object", "function"].includes(typeof Lock) && Lock !== null) natives.add(Lock)
if (["object", "function"].includes(typeof LockManager) && LockManager !== null) natives.add(LockManager)

//TODO: M

if (["object", "function"].includes(typeof NamedNodeMap) && NamedNodeMap !== null) natives.add(NamedNodeMap)
if (["object", "function"].includes(typeof NavigationPreloadManager) && NavigationPreloadManager !== null) natives.add(NavigationPreloadManager)
if (["object", "function"].includes(typeof Navigator) && Navigator !== null) natives.add(Navigator)
if (["object", "function"].includes(typeof Node) && Node !== null) natives.add(Node)
if (["object", "function"].includes(typeof NodeFilter) && NodeFilter !== null) natives.add(NodeFilter)
if (["object", "function"].includes(typeof NodeIterator) && NodeIterator !== null) natives.add(NodeIterator)
if (["object", "function"].includes(typeof NodeList) && NodeList !== null) natives.add(NodeList)
if (["object", "function"].includes(typeof Notification) && Notification !== null) natives.add(Notification)
if (["object", "function"].includes(typeof Number) && Number !== null) natives.add(Number)
if (["object", "function"].includes(typeof navigator) && navigator !== null) natives.add(navigator)

if (["object", "function"].includes(typeof Object) && Object !== null) natives.add(Object)
if (["object", "function"].includes(typeof OfflineAudioCompletionEvent) && OfflineAudioCompletionEvent !== null) natives.add(OfflineAudioCompletionEvent)
if (["object", "function"].includes(typeof OfflineAudioContext) && OfflineAudioContext !== null) natives.add(OfflineAudioContext)
if (["object", "function"].includes(typeof OffscreenCanvas) && OffscreenCanvas !== null) natives.add(OffscreenCanvas)
if (["object", "function"].includes(typeof OffscreenCanvasRenderingContext2D) && OffscreenCanvasRenderingContext2D !== null) natives.add(OffscreenCanvasRenderingContext2D)
if (["object", "function"].includes(typeof Option) && Option !== null) natives.add(Option)
if (["object", "function"].includes(typeof OscillatorNode) && OscillatorNode !== null) natives.add(OscillatorNode)
if (["object", "function"].includes(typeof OverconstrainedError) && OverconstrainedError !== null) natives.add(OverconstrainedError)
if (["object", "function"].includes(typeof onabort) && onabort !== null) natives.add(onabort)
if (["object", "function"].includes(typeof onafterprint) && onafterprint !== null) natives.add(onafterprint)
//TODO: on

//TODO: P

if (["object", "function"].includes(typeof queueMicrotask) && queueMicrotask !== null) natives.add(queueMicrotask)

//TODO: R

//TODO: S

if (["object", "function"].includes(typeof Text) && Text !== null) natives.add(Text)
if (["object", "function"].includes(typeof TextDecoder) && TextDecoder !== null) natives.add(TextDecoder)
if (["object", "function"].includes(typeof TextDecoderStream) && TextDecoderStream !== null) natives.add(TextDecoderStream)
if (["object", "function"].includes(typeof TextEncoder) && TextEncoder !== null) natives.add(TextEncoder)
if (["object", "function"].includes(typeof TextEncoderStream) && TextEncoderStream !== null) natives.add(TextEncoderStream)
if (["object", "function"].includes(typeof TextMetrics) && TextMetrics !== null) natives.add(TextMetrics)
if (["object", "function"].includes(typeof TextTrack) && TextTrack !== null) natives.add(TextTrack)
if (["object", "function"].includes(typeof TextTrackCue) && TextTrackCue !== null) natives.add(TextTrackCue)
if (["object", "function"].includes(typeof TextTrackCueList) && TextTrackCueList !== null) natives.add(TextTrackCueList)
if (["object", "function"].includes(typeof TextTrackList) && TextTrackList !== null) natives.add(TextTrackList)
if (["object", "function"].includes(typeof TimeRanges) && TimeRanges !== null) natives.add(TimeRanges)
if (["object", "function"].includes(typeof Touch) && Touch !== null) natives.add(Touch)
if (["object", "function"].includes(typeof TouchEvent) && TouchEvent !== null) natives.add(TouchEvent)
if (["object", "function"].includes(typeof TransformStream) && TransformStream !== null) natives.add(TransformStream)
if (["object", "function"].includes(typeof TransformStreamDefaultController) && TransformStreamDefaultController !== null) natives.add(TransformStreamDefaultController)
if (["object", "function"].includes(typeof TransitionEvent) && TransitionEvent !== null) natives.add(TransitionEvent)
if (["object", "function"].includes(typeof TreeWalker) && TreeWalker !== null) natives.add(TreeWalker)
if (["object", "function"].includes(typeof TypeError) && TypeError !== null) natives.add(TypeError)

if (["object", "function"].includes(typeof UIEvent) && UIEvent !== null) natives.add(UIEvent)
if (["object", "function"].includes(typeof URIError) && URIError !== null) natives.add(URIError)
if (["object", "function"].includes(typeof URL) && URL !== null) natives.add(URL)
if (["object", "function"].includes(typeof URLSearchParams) && URLSearchParams !== null) natives.add(URLSearchParams)
if (["object", "function"].includes(typeof Uint16Array) && Uint16Array !== null) natives.add(Uint16Array)
if (["object", "function"].includes(typeof Uint32Array) && Uint32Array !== null) natives.add(Uint32Array)
if (["object", "function"].includes(typeof Uint8Array) && Uint8Array !== null) natives.add(Uint8Array)
if (["object", "function"].includes(typeof Uint8ClampedArray) && Uint8ClampedArray !== null) natives.add(Uint8ClampedArray)
if (["object", "function"].includes(typeof unescape) && unescape !== null) natives.add(unescape)

if (["object", "function"].includes(typeof VBArray) && VBArray !== null) natives.add(VBArray)
if (["object", "function"].includes(typeof VTTCue) && VTTCue !== null) natives.add(VTTCue)
if (["object", "function"].includes(typeof VTTRegion) && VTTRegion !== null) natives.add(VTTRegion)
if (["object", "function"].includes(typeof ValidityState) && ValidityState !== null) natives.add(ValidityState)
if (["object", "function"].includes(typeof VarDate) && VarDate !== null) natives.add(VarDate)
if (["object", "function"].includes(typeof VideoColorSpace) && VideoColorSpace !== null) natives.add(VideoColorSpace)
if (["object", "function"].includes(typeof VideoPlaybackQuality) && VideoPlaybackQuality !== null) natives.add(VideoPlaybackQuality)
if (["object", "function"].includes(typeof VisualViewport) && VisualViewport !== null) natives.add(VisualViewport)
if (["object", "function"].includes(typeof visualViewport) && visualViewport !== null) natives.add(visualViewport)

//TODO: W

if (["object", "function"].includes(typeof XMLDocument) && XMLDocument !== null) natives.add(XMLDocument)
if (["object", "function"].includes(typeof XMLHttpRequest) && XMLHttpRequest !== null) natives.add(XMLHttpRequest)
if (["object", "function"].includes(typeof XMLHttpRequestEventTarget) && XMLHttpRequestEventTarget !== null) natives.add(XMLHttpRequestEventTarget)
if (["object", "function"].includes(typeof XMLHttpRequestUpload) && XMLHttpRequestUpload !== null) natives.add(XMLHttpRequestUpload)
if (["object", "function"].includes(typeof XMLSerializer) && XMLSerializer !== null) natives.add(XMLSerializer)
if (["object", "function"].includes(typeof XPathEvaluator) && XPathEvaluator !== null) natives.add(XPathEvaluator)
if (["object", "function"].includes(typeof XPathExpression) && XPathExpression !== null) natives.add(XPathExpression)
if (["object", "function"].includes(typeof XPathResult) && XPathResult !== null) natives.add(XPathResult)
if (["object", "function"].includes(typeof XSLTProcessor) && XSLTProcessor !== null) natives.add(XSLTProcessor)

for (const object of natives) {

    const keys = Reflect.ownKeys(object)
    if ("constructor" in object)
        keys.push("constructor")

    for (const key of keys) {
        try {
            const value = Object.getOwnPropertyDescriptor(object, key)?.value || object[key]

            console.log(value)

            if (["object", "function"].includes(typeof value) && value !== null) {
                natives.add(value)
            }
        } catch { }
    }

}

export default Array.from(natives)